# {{- range .Values.rolebinding }}
# {{- $role := .role }}
# {{- $groupid := .groupid }}
# {{- range .projects }}
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: {{ $role }}-{{ . }}
#   namespace: {{ . }}
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: {{ $role }}
# subjects:
# - apiGroup: rbac.authorization.k8s.io
#   kind: Group
#   name: {{ $groupid }}
# ---
# {{- end }}
# {{- end }}
