{{- if .Values.integrations.eso.add -}}
  {{- if .Values.integrations.logforwarder.enabled -}}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.integrations.logforwarder.azuremonitor.secretname }}-external-secret
  namespace: openshift-monitoring
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.integrations.eso.clustersecretstore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.integrations.logforwarder.azuremonitor.secretname }}
    template:
      type: Opaque
  data:
  - secretKey: clientSecret
    remoteRef:
      key: secret/{{ .Values.integrations.logforwarder.azuremonitor.akvname }}
  {{- end -}}
{{- end -}}