
{{- if .Values.integrations.userworkloadmonitoring.enabled -}}
apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |
    prometheus:
      retention: "15d"
      volumeClaimTemplate:
        spec:
          storageClassName: managed-premium
          resources:
            requests:
              storage: "300Gi"
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
{{- end -}}