{{- if .Values.integrations.eso.add -}}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: entraid-idp-eso
  namespace: openshift-config
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.integrations.eso.clustersecretstore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.integrations.entraid.secretname }}
    template:
      type: Opaque
  data:
  - secretKey: clientSecret
    remoteRef:
      key: secret/{{ .Values.integrations.entraid.secretKeyinAKV }}
{{- end -}}